Match table for db
sistemasweb5/MatchService pull request #1
Opened 2024-10-22 21:49 UTC by diego-centella-jalafund

2024-10-22 22:04 UTC, luis-espinoza-jalafund requested changes

2024-10-22 22:04 UTC, luis-espinoza-jalafund commented on src/Program.cs
> +builder.Services.AddSingleton<IDbConnection>((sp) =>
It is not necessary to add this, the table is already created with the script without using Services.AddSingleton.

2024-10-22 22:04 UTC, luis-espinoza-jalafund commented on src/Program.cs
> +using Npgsql; // Para NpgsqlConnection
Do not leave comments without utility

2024-10-22 22:04 UTC, luis-espinoza-jalafund commented on src/Data/Scripts/Match.sql
> +);
Missing endline

2024-10-22 22:04 UTC, luis-espinoza-jalafund commented on src/Domain/Match.cs
> +}
Missing endline

2024-10-22 22:04 UTC, luis-espinoza-jalafund commented on src/Data/Scripts/Match.sql
> +    id SERIAL PRIMARY KEY,
The ID should be a GUIID

2024-10-22 22:04 UTC, luis-espinoza-jalafund commented on src/Domain/Match.cs
> +    public int Id { get; set; }
The ID should be a GUID not an int

2024-10-22 22:06 UTC, luis-espinoza-jalafund commented
We must also add the JSON that we will use for the User and Workers in order to make the connections between these tables and apply the match.

2024-10-22 22:07 UTC, luis-espinoza-jalafund commented on src/Data/Scripts/Match.sql
> +    skill VARCHAR(255) NOT NULL,
the skills will be text only? what does the other group say about this?

2024-10-23 17:06 UTC, SebasthianSalpozz requested changes

2024-10-23 17:06 UTC, SebasthianSalpozz commented on src/Persistence/Jobs.json
> +        "id": "worker-uuid-1",
Tus trabajadores no tienen ningun tipo de ubicacion para ir ver si estan en la zona del usuario

2024-10-23 17:06 UTC, SebasthianSalpozz commented on src/Persistence/Jobs.json
> +        "name": "Juan Pérez",
Tus usuarios no tienen ningun tipo de ubicacion para ir buscando alrededor

2024-10-23 17:08 UTC, SebasthianSalpozz reviewed
Talvez para manejar las ubicaciones podriamos usar la investigacion de postgis q esta en la wiki y asi poder realizar solo un query y todo esto que este seteado en una base de datos y solo realizar la consulta

2024-10-25 02:37 UTC, luis-espinoza-jalafund requested changes

2024-10-25 02:37 UTC, luis-espinoza-jalafund commented on src/Domain/Match.cs
> +    public required string Worker { get; set; }
is this the id of the user and worker? if so, why don't they have “ID” in the variable name?

2024-10-25 02:37 UTC, luis-espinoza-jalafund commented on src/Data/Scripts/Match.sql
> +    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
Here you use a postgres extension, did you make sure it is installed automatically for everyone?

2024-10-25 02:37 UTC, luis-espinoza-jalafund commented on src/Program.cs
> +builder.Services.AddTransient<DbInitializer>();
This is also innecesary

2024-10-25 02:37 UTC, luis-espinoza-jalafund commented on src/Data/Scripts/DataSQL.sql
> +);
The work schedule column is missing, it is necessary to know the worker's availability.

2024-10-25 02:37 UTC, luis-espinoza-jalafund commented on src/Data/Scripts/DataSQL.sql
> +
the Speciality and WorkSchedule tables are missing

2024-10-25 11:06 UTC, luis-espinoza-jalafund approved these changes

2024-10-25 11:34 UTC, luis-espinoza-jalafund requested changes

2024-10-25 11:34 UTC, luis-espinoza-jalafund commented on src/Data/Scripts/DataSQL.sql
> +
the project stopped compiling because of missing postgis dependencies, do a rebase and update your branch

2024-10-25 12:53 UTC, luis-espinoza-jalafund approved these changes

2024-10-25 15:29 UTC, closed without merging